name: Daily Pull and Vulnerability Scan

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  pull-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.THE_DOCKER_USER }}
        password: ${{ secrets.THE_DOCKER_PASS }}

    - name: Pull Docker image
      run: |
        IMAGE_NAME="jasonculligan/nmap-in-alpine:latest"
        docker pull $IMAGE_NAME
      env:
        IMAGE_NAME: jasonculligan/nmap-in-alpine:latest

    - name: Scan Docker image with Trivy
      id: scan_image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        ignore-unfixed: true  # Optional: set to false to capture all vulnerabilities
        format: "table"
        args: "--exit-code 1"

    - name: Rebuild and push updated image if vulnerabilities found
      if: failure()  # Only runs if the previous step fails (exit code 1)
      run: |
        # Rebuild the image using the latest base image
        docker build --no-cache -t $IMAGE_NAME .
        docker push $IMAGE_NAME
      env:
        IMAGE_NAME: jasonculligan/nmap-in-alpine:latest
